name: Build Rust Library for Windows and macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc
    
    - name: Build Windows DLL
      run: cargo build --release
    
    - name: Upload Windows DLL
      uses: actions/upload-artifact@v4
      with:
        name: windows-dll
        path: target/release/activity_monitor.dll
  
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-darwin
    
    - name: Build macOS dylib
      run: cargo build --target aarch64-apple-darwin --release
    
    - name: Upload macOS dylib
      uses: actions/upload-artifact@v4
      with:
        name: macos-dylib
        path: target/aarch64-apple-darwin/release/libactivity_monitor.dylib